
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
  training-service:
    build: ./training-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
  detection-service:
    build: ./detection-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
  python-api:
    image: python:3.9
    volumes:
      - ./python-api:/app
    working_dir: /app
    command: bash -c "python main.py"
    ports:
      - "5000:5000"